name: rebase
on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch: # Allows manual runs
jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # This explicitly grants write permission to repository contents
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0  # Fetch full history for pull/rebase to work properly

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r hindu-news-app/requirements.txt

      - name: Run scrapper
        run: |
          cd hindu-news-app
          python scrapper.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          
          git add hindu-news-app/news_data.txt
          git commit -m "Auto-update news data" || echo "No changes to commit"

          # Pull latest changes with rebase to avoid non-fast-forward errors
          git pull origin main --rebase

          # Push changes after successful rebase
          git push origin main
